# Generated by Django 4.1 on 2022-10-27 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreR', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fechareserva', models.DateTimeField(auto_now_add=True)),
                ('numeroPersonas', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)])),
                ('estado', models.IntegerField(choices=[(1, 'Reservado'), (2, 'Completada'), (3, 'Anulada'), (4, 'No Asisten')], default=1)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
